#!/bin/bash -e
echo $VPN_PEER_HOST > /etc/wireguard/host
if [ ! -f "/etc/wireguard/wg0" ]; then
  cat <<EOF > /etc/wireguard/wg0.conf
[Interface]
PrivateKey = $(cat /run/secrets/client_privatekey)
Address = ${IPV4_ADDRESS}
DNS = ${IPV4_DNS}
PostUp=/etc/wireguard/postUp
PostDown=kill SIGRTMIN+3 1
[Peer]
PublicKey = $(cat /run/secrets/server_publickey)
AllowedIPs = 0.0.0.0/0
Endpoint = ${VPN_PEER_HOST}:${VPN_PEER_PORT}
EOF
fi

systemctl enable wg-quick@wg0

exec /sbin/init
